
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://tedelman91.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "tedelman"
title: "{ Data Driven }"
description: "Tales of life and data."
keywords: "Tales of life and data."
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "/img/Rain.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "If you're parachute doesn't open don't worry; you have the rest of your life to figure it out."
  - text: "A fart is the lonesome cry of an imprisoned turd."
  - text: "My time is like a toddler in a tiara; precious and short."
  - text: "The tree remembers what the axe forgets."
  - text: "Instead of Netflix and chill; intelligent conversation and chill."
  - text: "Life's as kind as you let it be."
  - text: "Most people die at 25 and aren't buried until 75."
  - text: "Amaze me with your brilliance or dazzle me with your bullshit."
  - text: "I'm an average man with above average dreams."
  - text: "I'm just a God waiting for you lazy bastards to build me a temple."
  - text: "Yes, my friends, all that you say is true. I have had a long life full of troubles. But there is one curious fact about them – nine-tenths of them never happened."
  - text: "Be fearless in the pursuit of that which enriches and excites your soul."
  - text: "Success is never final and failure is never fatal. It's courage that counts."
  - text: "Love the girl that can make your world the most beautiful."
  - text: "Your right now doesn't have to be your future."
  - text: "Many excellent words are ruined by too definite a knowledge of their meaning."

me-img: "/img/dmb.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True


disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"


###########
# Contact #
###########

email: "edelmatj@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Tyler is a developer by day and ski junki/outdoor enthusiant with any free time he has."
author_blurb_image: "/img/Coffee.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/tyler-edelman-622a1144"
  - title: "twitter"
    url: "https://twitter.com/tyler_edelman"
  - title: "github"
    url: "https://github.com/tedelman91"


############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
